config/routes.rb
 Rails.application.routes.draw do
  devise_for :users
  root to: 'villas#home'
  get '/search', to: 'villas#search'
  resources :villas, only: [:new, :create]
  resources :villas, only: [:show] do
    resources :bookings, only: [:new, :create]
    # resources :reviews, only: [:new, :create]
  end
  resources :bookings, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :villa
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/villa.rb
class Villa < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :reviews
  has_many_attached :photos, dependent: :destroy

  include PgSearch::Model
  pg_search_scope :search_by_location,
    against: [:location],
    using: {
      tsearch: { prefix: true }
    }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :find_villa, only: [:new, :create]
  before_action :set_user, only: [:index, :create]
  def index
    @bookings = Booking.where(user_id: @uid)
    @upcoming_bookings = @bookings.select { |booking| booking.date >= Date.today }
    @past_bookings = @bookings.select { |booking| booking.date < Date.today }
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @user = User.find(@uid)
    @booking.villa = @villa
    @booking.user = @user
    @booking.is_accepted = false
    if @booking.save
      redirect_to bookings_path
    else
      render :new
    end
  end

  private

  def find_villa
    @villa = Villa.find(params[:villa_id])
  end

  def set_user
    @uid = User.where(email: "booking@gmail.com")[0].id
  end

  def booking_params
    params.require(:booking).permit(:number_of_nights, :date)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/villas_controller.rb
class VillasController < ApplicationController
  before_action :set_user, only: [:create]

  def home
    @villa = Villa.new
  end

  def new
    @villa = Villa.new
  end

  def create
    @villa = Villa.new(villa_params)
    @user = User.find(@uid)
    @villa.user = @user
    if @villa.save
      redirect_to villa_path(@villa)
    else
      render :new
    end
  end

  def search
    @villas = Villa.search_by_location(params[:location]).select do |villa|
        villa[:number_of_beds].to_i >= params[:guests].to_i
      end
  end

  def show
    @villa = Villa.find(params[:id])
  end

  private
  def set_user
    @uid = User.where(email: "hello@gmail.com")[0].id
  end

  def villa_params
    params.require(:villa).permit(:title, :description, :location, :services, :price_per_night, :number_of_bedrooms, :number_of_bathrooms, :number_of_beds, photos: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<% if @bookings == []  %>
  <h2><%= "You have no upcoming experience. Book one !"%></h2>
<% else %>
  <% if @upcoming_bookings != []  %>
    <div class="bookings-status-box">
      <div class="bookings-status-box-content">
        <h1><%= "Your upcoming experiences"%></h1>
      </div>
    </div>
    <% @upcoming_bookings.each do |booking| %>
      <div class="result-container">
        <div class="result-card">
          <div class="result-card_content">
            <div class="result-details">
              <div>
                <h1>
                  <strong><%= booking.villa[:title] %></strong>
                </h1>
              </div>
              <hr />
              <div id="description">
                <h2><%= booking.villa[:description] %></h2>
              </div>
              <div id="details">
                <p><strong>Date:</strong> <%= booking.date %></p>
                <p><strong>Location:</strong> <%= booking.villa[:location] %></p>
              </div>
              <div class="card-button">
                <strong><%= link_to "View experience details", booking_path(booking) %></strong>
              </div>
            </div>
          </div>
        </div>
      <%= cl_image_tag booking.villa.photos.first.key %>
      </div>
    <% end %>
  <% end %>
<% end %>
<% if @past_bookings != []  %>
    <div class="past-experiences-box">
      <div class="bookings-status-box">
        <div class="bookings-status-box-content">
          <h1><%= "Your past experiences"%></h1>
        </div>
      </div>
      <% @past_bookings.each do |booking| %>
        <div class="result-container">
          <div class="result-card">
            <div class="result-card_content">
              <div class="result-details">
                <div>
                  <h1>
                    <strong><%= booking.villa[:title] %></strong>
                  </h1>
                </div>
                <hr />
                <div id="description">
                  <h2><%= booking.villa[:description] %></h2>
                </div>
                <div id="details">
                  <p><strong>Date:</strong> <%= booking.date %></p>
                  <p><strong>Location:</strong> <%= booking.villa[:location] %></p>
                </div>
                <div class="card-button">
                  <strong><%= link_to "View experience details", booking_path(booking) %></strong>
                </div>
              </div>
            </div>
          </div>
        <%= cl_image_tag booking.villa.photos.first.key %>
        </div>
      <% end %>
    </div>
  <% end %>

app/views/bookings/new.html.erb
<section class="display-flex">
  <div class="background content container">
    <h1>New booking</h1>
    <div class="search-villa-form">
      <%= simple_form_for [@villa, @booking] do |f| %>
        <div class="input-fields">
          <%= f.input :date, class: "form-control" %>
          <%= f.input :number_of_nights, class: "form-control" %>
        </div>
        <%= f.button :submit, 'Book this experience', class: "search-button" %>
      <% end %>
    </div>
  </div>
</section>

app/views/bookings/show.html.erb
<h2><strong>Booking deatails</strong></h2>
<br>
<h3>Date: <%= @booking.date %></h3>
<br>
<h3>Description: <%= @booking.villa[:description] %></h3>
<h3>Location: <%= @booking.villa[:location] %></h3>

<h3>Bedrooms: <%= @booking.villa[:number_of_bedrooms] %></h3>
<h3>Bathrooms: <%= @booking.villa[:number_of_bathrooms] %></h3>

<h3>Total price: <%= @booking.villa[:price_per_night]* @booking.number_of_nights %>€</h3>

<h3>Services provided: <%= @booking.villa[:services] %></h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@100&family=Lato:wght@100&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/715418b494.js" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css2?family=Material+Icons"
      rel="stylesheet">

    <title>GoldenPlaces</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <% unless params[:action] == "home"  %>
      <%= render 'shared/navbar' %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar d-flex justify-content-between">
  <%= link_to "Golden Places", root_path %>
  <div>
    <%= link_to "Search", root_path %>
    <%= link_to "Bookings", bookings_path %>
  </div>
</div>

app/views/villas/home.html.erb
<section class="display-flex">
  <div class="first_part">
    <div class="container">
      <div class="background">
        <div class="navbar d-flex justify-content-between">
          <%= link_to "Golden Places", root_path %>
          <div>
            <%= link_to "Search", root_path %>
            <%= link_to "Bookings", bookings_path %>
          </div>
        </div>
        <div class="content">
          <h2>Which place is your next discovery?</h2>
          <div class="search-villa-form">
            <%= form_tag search_path, method: :get do %>
              <div class="input-fields">
                <p>Location</p>
                <%= text_field_tag :location,
                  params[:location],
                  class: "form-control",
                  placeholder: "San Francisco"
                %>
                <br>
                <p>Number of guests</p>
                <%= text_field_tag :guests,
                  params[:guests],
                  class: "form-control",
                  placeholder: "4"
                %>
              </div>
              <%= submit_tag "Search", class: "search-button" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="second_part">
    <img class="img_home" src="https://s3-us-west-2.amazonaws.com/maven-user-photos/bigblendedfamily/parenting/7nKsL4HrtkaXmFAI6iZ3ww/tyuYlAHv90KmzPc-MJU3DQ" alt="">
  </div>
</section>

app/views/villas/index.html.erb
<div class="container">
  <h2>Which place is your next discovery?</h2>
  <div class="form-box">
    <%= simple_form_for(@villa) do |f| %>
      <%= f.input :location, error: 'Please specify a location' %>
      <%= f.input :number_of_beds, error: 'Please specify a location', label: 'Number of guests' %>
      <%= f.button :submit, class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/villas/new.html.erb
<div class="container">
  <h1>New villa</h1>
  <div class="form-box">
    <%= simple_form_for(@villa) do |f| %>
      <%= f.input :title %>
      <%= f.input :description %>
      <%= f.input :location %>
      <%= f.input :services %>
      <%= f.input :price_per_night %>
      <%= f.input :number_of_bedrooms %>
      <%= f.input :number_of_bathrooms %>
      <%= f.input :number_of_beds, label: 'Number of guests' %>
      <%= f.input :photos, as: :file, input_html: { multiple: true } %>
      <%= f.button :submit, class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/villas/search.html.erb
<!-- Implement search results -->
<% if @villas == []  %>
  <h2><%= "No villa corresponds to your will"%></h2>
<% else %>
  <% @villas.each do |villa| %>
    <div class="result-container">
      <div class="result-card">
        <div class="result-card_content">
          <div class="result-details">
            <div>
              <h1>
                <strong><%= villa.title %></strong>
              </h1>
            </div>
            <hr />
            <div id="description">
              <h2><%= villa.description %></h2>
            </div>
            <div id="details">
              <p><strong>Location:</strong> <%= villa.location %></p>
              <p><strong>Max. number of guests:</strong> <%= villa.number_of_beds %></p>
            </div>
            <div class="card-button">
              <strong><%= link_to "See more...", villa_path(villa) %></strong>
            </div>
          </div>
        </div>
      </div>
    <%= cl_image_tag villa.photos.first.key %>
    </div>
  <% end %>
<% end %>

app/views/villas/show.html.erb
<link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Heebo:wght@100&family=Lato:wght@100&display=swap" rel="stylesheet">

<div id="carouselExampleIndicators" class="carousel slide carousel-fade" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <%= cl_image_tag @villa.photos.first.key %>
    </div>
    <% @villa.photos.drop(1).each do |photo| %>
    <div class="carousel-item">
      <%= cl_image_tag photo.key %>
    </div>
    <% end %>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
<div class="text-center" id="villa-detail">
  <h1 class="mt-3"><strong><%= @villa.title %></strong></h1>
  <i id="star" class="far fa-star"></i> <i id="star" class="far fa-star"></i> <i id="star" class="far fa-star"></i> <i id="star" class="far fa-star"></i> <i id="star" class="far fa-star"></i>
  <!-- <p> Ceci est une description </p> -->
  <p>Description: <%= @villa.description %></p>
  <p>Location: <%= @villa.location %></p>
  <p>Bedrooms: <%= @villa.number_of_bedrooms %></p>
  <p>Bathrooms: <%= @villa.number_of_bathrooms %></p>
  <p>Max. number of guests: <%= @villa.number_of_beds %></p>
  <p class="mb-5">Price per night: <%= @villa.price_per_night %>€</p>
</div>
<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d65079.23504493018!2d-122.41035910409124!3d37.7638408277714!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x80859a6d00690021%3A0x4a501367f076adff!2sSan%20Francisco%2C%20Californie%2C%20%C3%89tats-Unis!5e0!3m2!1sfr!2sfr!4v1606483946490!5m2!1sfr!2sfr" width="300" height="200" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
  <%= link_to "Book this place", new_villa_booking_path(@villa), class: "button", id:"button-book-villa" %>
<div id="service" class="text-center d-flex align-items-center justify-content-center">
  <div>
    <h2 style="color: #2F3740">Services:</h2> <p><%= @villa.services %></p>
    <i class="material-icons mt-4">flight</i>
    <i class="material-icons mt-4">sports_tennis</i>
    <i class="material-icons mt-4">restaurant_menu</i>
    <i class="material-icons mt-4" style="margin-right: 0">spa</i>
  </div>

</div>
<div class="container">
  <h2 class="mt-5 mb-5">Reviews</h2>
  <div class="flexbox">
    <div class="review">
      <div class="comments mb-4 d-flex align-items-center">
        <img src="https://res.cloudinary.com/jackycloud44/image/upload/v1606404485/simon-marsault-ZNaL-IDTbZc-unsplash_hgpe3f.jpg" alt="" class="avatar">
       <p class="mb-4 ml-3 mr-3">Je recommande cette superbe villa! Nous avons passé 3 jours tres agréables! L’accueil et la cuisine sont au top! Merci à Fatiha et Patrice.
Les chambres sont spacieuses et propres.
Les transferts gratuits très pratiques .
À faire!!</p>
      </div>
      <div class="comments mb-4 d-flex align-items-center">
        <img src="https://res.cloudinary.com/jackycloud44/image/upload/v1606404484/stefan-stefancik-QXevDflbl8A-unsplash_mdvbxu.jpg" alt="" class="avatar">
      <p class="mb-4 ml-3 mr-3">Amazing contemporary property. Easily hosts 10 people in double bedrooms. Exquisite artwork was a lovely touch. We went for a long birthday weekend with friends, but I could equally see spending a family vacation in this fantastic property.</p>
      </div>
      <div class="comments mb-4 d-flex align-items-center">
        <img src="https://res.cloudinary.com/jackycloud44/image/upload/v1606473846/matt-sings-ixmVe2qr8TM-unsplash_pmbdwq.jpg" alt="" class="avatar">
      <p class="mb-4 ml-3 mr-3">J ai été ravi de mon séjour au sein de cette magnifique villa. Elle est spacieuse, joli et bien entretenu. Le personnel est compétent et répond à nos attentes. La restauration est très bonnes et la cuisinière est très agréable. Sérénité et calme sont garantis.
Un séjour réussi.</p>
      </div>
       </div>
    <div id="card_description">
      <img src="https://res.cloudinary.com/jackycloud44/image/upload/v1606404463/jack-finnigan-rriAI0nhcbc-unsplash_fq8bns.jpg" alt="" class="avatar">
      <p> Welcome, </p>
      <p class="mb-2">“Mijas, a villa that will amaze you ! 3 bedroom, 2 bathroom, bult 137m2, terrace 19m2, parking, storage. - 4 bedroom, 3 bathroom, bult 144m2, terrace 162m2, parking, storage, garden. Sea views, Spa, 4 pools, Putting green, Paddle tenis court, Gym, Social Room, Walking distance to beach and golf.”</p>
    </div>
  </div>
</div>